#!/bin/bash

FILE=$1
NAME=$2

#This takes .tar.gz files and extracts them into fast5 files

mkdir ~/darter/f5_untar/${NAME}; 
echo "made directory : f5_untar/"${NAME}

echo "******************************************************************"
echo $FILE;
echo "******************************************************************"
sleep 10
time tar -xvf $FILE -C ~/darter/f5_untar/${NAME} 
echo "<<<<<<<<<<<<<<<<<<<UNTAR COMPLETE>>>>>>>>>>>>>>>>>>>>>>>>"

#Converge files

echo "merging file path: ~/darter/f5_untar/"${NAME}
sleep 10
single_to_multi_fast5 --input_path ~/darter/f5_untar/${NAME} --save_path ~/darter/multif5/${NAME} --filename_base batch_output --batch_size 100 --recursive

#Convert the multireads into pod5 format

echo "::::::::::::::CONVERTING:::::::::::::"
sleep 10
pod5 convert fast5 ~/darter/multif5/${NAME} --output /mnt/d/SGNEX/p5/${NAME%.*}.pod5

#clean up processing directories

echo "%%%%%%%%%%%%%%%CLEANING f5_untar/"${NAME}"%%%%%%%%%%%%%%%%%%"
find ~/darter/f5_untar/${NAME} -type f  -exec rm {} \;
echo "%%%%%%%%%%%%%%%CLEANING multif5/"${NAME}"%%%%%%%%%%%%%%%%%%"
find ~/darter/multif5/${NAME} -type f  -exec rm {} \;
 