#!/bin/bash 

SIRV_REF=/mnt/d/refData/lrgasp_grch38_sirvs.fasta
SIRV_ANNO=/mnt/d/refData/lrgasp_gencode_v38_sirvs.gtf
STRING_GTF=/mnt/d/SGNEX/string/merged_transcripts.gtf
INDEX=/mnt/d/SGNEX/sally/sal_string_index

echo "###################################################"
echo "MAKE SURE IN CODNA SALTY ENV"
echo "###################################################"


for NAME in "$@"; do
echo "::SALMONING::> '$NAME'"
 salmon quant -t /mnt/d/SGNEX/String/transcripts.fa -l U -a /mnt/d/SGNEX/mini_bam/${NAME}.bam -o /mnt/d/SGNEX/sal_count/bam_${NAME}_salmon_output
# time salmon quant -i $INDEX -l A -r /mnt/d/SGNEX/fq/${NAME}.fastq  -o /mnt/d/SGNEX/sal_count/${NAME}_salmon_output
done

