#!/bash/bin

SIRV_REF=/mnt/d/refData/lrgasp_grch38_sirvs.fasta
SIRV_ANNO=/mnt/d/refData/lrgasp_gencode_v38_sirvs.gtf
STRING_GTF=/mnt/d/SGNEX/string/merged_transcripts.gtf
INDEX=/mnt/d/SGNEX/sally/sal_string_index

NAME=$1
#for NAME in "$@"; do
#GTF_ALL+=" /mnt/d/SGNEX/String/${NAME}.gtf"
    #echo $GTF_ALL
#done

#echo "#MERGING"
#time stringtie --merge -G $SIRV_ANNO -o /mnt/d/SGNEX/String/merged_transcripts.gtf $GTF_ALL

#must be done in salty conda env
echo "#GEOFF"
~/gffread/gffread -w /mnt/d/SGNEX/String/A_d_r1r3_transcripts.fa -g /mnt/d/refData/lrgasp_grch38_sirvs.fasta /mnt/d/SGNEX/GTF_files/stringtie/A_d_r1r3_transcripts.gtf

echo "#INDEXING"

salmon index -t /mnt/d/SGNEX/String/${NAME}_transcripts.fa  -i /mnt/d/SGNEX/sally/sal_${NAME}_index
almon index -t /mnt/d/SGNEX/String/${NAME}_transcripts.fa  -i /mnt/d/SGNEX/sally/sal_${NAME}_index


echo "::SALMONING::> '$NAME'"
 salmon quant -t /mnt/d/SGNEX/String/${NAME}_transcripts.fa -l U -a /mnt/d/SGNEX/mini_bam/${NAME}.bam -o /mnt/d/SGNEX/sal_count/bam_${NAME}_salmon_output
time salmon quant -i ~/darter/refData/salindex -l U -r /mnt/d/SGNEX/String/A_d_r1r3_transcripts.fa -o /mnt/d/SGNEX/sal_count/${NAME}_salmon_output_1502


time salmon quant -i /mnt/d/SGNEX/sally/sal_string_index -l U -r /mnt/d/SGNEX/fq/A_d_r1r3.fastq -o /mnt/d/SGNEX/sal_count/${NAME}_fq_count