#!/bin/bash 

SIRV_REF=/mnt/d/refData/lrgasp_grch38_sirvs.fasta
SIRV_ANNO=/mnt/d/refData/lrgasp_gencode_v38_sirvs.gtf
GTF_LIST=/mnt/d/SGNEX/String/gtf_list.txt


for NAME in "$@"; do
GTF_ALL+=" /mnt/d/SGNEX/String/${NAME}.gtf"
    echo $GTF_ALL
done


   time stringtie --merge -G $SIRV_ANNO -o /mnt/d/SGNEX/String/merged_transcripts.gtf $GTF_ALL

